### ISSUE TITLE
Package not available 'Readline' - Windows

### ISSUE THREAD

**Issue by haseeb-heaven** [haseeb-heaven/Open-Code-Interpreter#2]
Kindly guide. (base) python -m 'code-llama' -md 'code'
Traceback (most recent call last):
```
  File "C:\Users\test\open-code-interpreter\[http://interpreter.py](https://t.co/Ag94dpbB78)", line 14, in <module>
    from libs.utility_manager import UtilityManager
  File "C:\Users\test\open-code-interpreter\libs\utility_manager.py", line 3, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

**Comment by haseeb-heaven** [comment]
User reported this issue only for Windows.
So you can you either use this 
```pip install pyreadline```

**Comment by haseeb-heaven** [comment]
Now made if optional to have command history
